name: CI 
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review_requested:
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load enviroment variables
        run: source .env

      - name: Copy ci.yaml file
        run: cp /path/to/ci.yaml ./ci.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 4.61.0

      # - name: Initialize Terraform
      #   run: terraform Init 

      - name: Apply Terraform
        env:
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make deploy 